# Generated by Django 2.2 on 2019-04-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_content', models.TextField()),
                ('blog_published', models.DateTimeField(verbose_name='Published ')),
            ],
        ),
    ]
